export const AVAILABLE_ICONS = [
    "Activity", "AlertCircle", "AlertTriangle", "Archive", "ArrowDown",
    "ArrowLeft", "ArrowRight", "ArrowUp", "Award", "BarChart", "BarChart2",
    "Bell", "Book", "BookOpen", "Bookmark", "Box", "Briefcase", "Calendar",
    "Camera", "Check", "CheckCircle", "ChevronDown", "ChevronLeft", "ChevronRight",
    "ChevronUp", "Circle", "Clipboard", "Clock", "Cloud", "Code", "Compass",
    "Copy", "CreditCard", "Database", "Delete", "Disc", "DollarSign", "Download",
    "Droplet", "Edit", "Edit2", "Edit3", "Eye", "EyeOff", "File", "FileMinus",
    "FilePlus", "FileText", "Film", "Filter", "Flag", "Folder", "FolderMinus",
    "FolderPlus", "Gift", "GitBranch", "GitCommit", "GitMerge", "GitPullRequest",
    "Globe", "Grid", "HardDrive", "Hash", "Headphones", "Heart", "HelpCircle",
    "Home", "Image", "Inbox", "Info", "Key", "Layers", "Layout", "LifeBuoy",
    "Link", "Link2", "List", "Loader", "Lock", "LogIn", "LogOut", "Mail",
    "Map", "MapPin", "Maximize", "Maximize2", "Menu", "MessageCircle",
    "MessageSquare", "Mic", "Minimize", "Minimize2", "Minus", "MinusCircle",
    "MinusSquare", "Monitor", "Moon", "MoreHorizontal", "MoreVertical",
    "MousePointer", "Move", "Music", "Navigation", "Octagon", "Package",
    "Paperclip", "Pause", "PauseCircle", "PenTool", "Percent", "Phone",
    "PhoneCall", "PhoneForwarded", "PhoneIncoming", "PhoneMissed", "PhoneOff",
    "PhoneOutgoing", "PieChart", "Play", "PlayCircle", "Plus", "PlusCircle",
    "PlusSquare", "Pocket", "Power", "Printer", "Radio", "RefreshCcw",
    "RefreshCw", "Repeat", "Rewind", "RotateCcw", "RotateCw", "Rss", "Save",
    "Scissors", "Search", "Send", "Server", "Settings", "Share", "Share2",
    "Shield", "ShieldOff", "ShoppingBag", "ShoppingCart", "Shuffle", "Sidebar",
    "SkipBack", "SkipForward", "Slack", "Slash", "Sliders", "Smartphone",
    "Smile", "Speaker", "Square", "Star", "StopCircle", "Sun", "Sunrise",
    "Sunset", "Tablet", "Tag", "Target", "Terminal", "Thermometer", "ThumbsDown",
    "ThumbsUp", "ToggleLeft", "ToggleRight", "Tool", "Trash", "Trash2",
    "Trello", "TrendingDown", "TrendingUp", "Triangle", "Truck", "Tv", "Twitch",
    "Twitter", "Type", "Umbrella", "Underline", "Unlock", "Upload", "UploadCloud",
    "User", "UserCheck", "UserMinus", "UserPlus", "UserX", "Users", "Video",
    "VideoOff", "Voicemail", "Volume", "Volume1", "Volume2", "VolumeX",
    "Watch", "Wifi", "WifiOff", "Wind", "X", "XCircle", "XOctagon", "XSquare",
    "Youtube", "Zap", "ZapOff", "ZoomIn", "ZoomOut"
];
