-- Create profiles table if it doesn't exist (PARTIAL FIX)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'coins') THEN
        ALTER TABLE profiles ADD COLUMN coins integer DEFAULT 100;
    END IF;
END $$;

-- Create Items table
create table if not exists items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price integer not null,
  icon text,
  type text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create User Inventory table
create table if not exists user_inventory (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  item_id bigint references items(id) not null,
  equipped boolean default false,
  api_data jsonb,
  purchased_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, item_id)
);

-- Seed Data (Conflict safe)
insert into items (name, price, icon, type) values 
('Fire Aura', 500, '🔥', 'aura'),
('Cool Shades', 300, '🕶️', 'accessory'),
('Wizard Hat', 800, '🧙‍♂️', 'accessory'),
('Golden Crown', 2000, '👑', 'accessory'),
('Neon Skin', 1500, '🎨', 'skin'),
('Pet Rock', 100, '🪨', 'pet')
on conflict do nothing;

-- Function
create or replace function purchase_item(item_id_input bigint)
returns jsonb
language plpgsql
security definer
as $$
declare
  user_coins int;
  item_price int;
  already_owned boolean;
  user_id_val uuid;
begin
  user_id_val := auth.uid();
  
  -- Check if already owned
  select exists(select 1 from user_inventory where user_id = user_id_val and item_id = item_id_input)
  into already_owned;
  
  if already_owned then
    return jsonb_build_object('success', false, 'message', 'Item already owned');
  end if;

  -- Get Item Price
  select price into item_price from items where id = item_id_input;
  if item_price is null then
    return jsonb_build_object('success', false, 'message', 'Item not found');
  end if;

  -- Get User Coins
  select coins into user_coins from profiles where id = user_id_val;
  
  if user_coins < item_price then
     return jsonb_build_object('success', false, 'message', 'Not enough coins');
  end if;

  -- Perform Transaction
  update profiles set coins = coins - item_price where id = user_id_val;
  insert into user_inventory (user_id, item_id) values (user_id_val, item_id_input);
  
  return jsonb_build_object('success', true, 'message', 'Purchase successful', 'new_balance', user_coins - item_price);
end;
$$;
