-- 1. Profiles Table (Extends Auth)
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  username text,
  avatar_url text,
  xp integer default 0,
  level integer default 1,
  monster_type text default 'blob',
  updated_at timestamp with time zone
);

-- 2. Habits Table
create table if not exists habits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  xp_reward integer default 10,
  completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Row Level Security (RLS) Policies
alter table profiles enable row level security;
alter table habits enable row level security;

-- Drop existing policies to avoid errors on run
drop policy if exists "Users can view own profile" on profiles;
drop policy if exists "Users can update own profile" on profiles;
drop policy if exists "Users can insert own profile" on profiles;
drop policy if exists "Users can crud own habits" on habits;

-- Re-create policies with INSERT permission
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
create policy "Users can insert own profile" on profiles for insert with check (auth.uid() = id); -- Added Insert Policy
create policy "Users can crud own habits" on habits for all using (auth.uid() = user_id);
